# Generated by Django 2.2 on 2019-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize_model',
            name='name',
            field=models.CharField(choices=[(0, '文字识别'), (1, '动物识别'), (2, '植物识别')], max_length=20, verbose_name='识别种类名称'),
        ),
    ]
